### ISSUE TITLE
The function sortByDate seems doesn't work

### ISSUE THREAD

**Issue by invisprints** [craigary/nobelium#102]
**Describe the bug**
I set the sortByDate to true in blog.config.js and find my blog posts don't sort by date.

**To Reproduce**
My blog link:
https://invisprints.vercel.app
 
GitHub repo:
https://github.com/invisprints/nobelium

Notion Page:
https://www.notion.so/c23506baa9334516ad2fb7f684cc37d1?v=60fbc9083a6d42328f314aa4ad120982

The nobelium version I use is [4bcc8b9]

**Screenshots**
<details>

![截屏2021-04-30 下午6 41 42](https://user-images.githubusercontent.com/15833553/116684670-cbfda480-a9e3-11eb-9680-ca26a6cad892.png)

</details>

**Platform:**

- OS: [macOS]
- Browser [safari]
- Version [4bcc8b9]

**Comment by craigary** [comment]
Bug fixed!
