### ISSUE TITLE
Syntax highlighting disappears due to refresh.

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#107]
**Describe the bug**

Syntax highlighting disappears due to refresh.

**To Reproduce**

- Open a post page with code.
- Click REFRESH
- Syntax highlighting disappears

**Expected behavior**

Syntax highlighting outlives refresh 

**Screenshots**

**Platform:**
iOS Firefox and other environments 
- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by craigary** [comment]
Duplicate #83
