### ISSUE TITLE
Deployment Error On Vercel

### ISSUE THREAD

**Issue by wz1616** [craigary/nobelium#108]
Here are logs![image](https://user-images.githubusercontent.com/62297116/116974630-01aad200-acf1-11eb-9cf0-022ba9405c70.jpeg)

**Comment by craigary** [comment]
Hi, would you mind to share your page id for me to test?

**Comment by wz1616** [comment]
> Hi, would you mind to share your page id for me to test?

ed4eb72bf7dd4499ae5fdfa9b796b9be

**Comment by craigary** [comment]
> > Hi, would you mind to share your page id for me to test?
> 
> ed4eb72bf7dd4499ae5fdfa9b796b9be

Thank you and I will test it soon.

**Comment by craigary** [comment]
![image](https://user-images.githubusercontent.com/10571717/117000476-b655eb00-ad13-11eb-8227-edba40549683.png)
Hi, I am able to deploy Nobelium with your page id w/out issue. Could you try to deploy again?

**Comment by wz1616** [comment]
Nope yet
> ![image](https://user-images.githubusercontent.com/10571717/117000476-b655eb00-ad13-11eb-8227-edba40549683.png)
> 
> Hi, I am able to deploy Nobelium with your page id w/out issue. Could you try to deploy again?

**Comment by craigary** [comment]
> Nope yet!![image](https://user-images.githubusercontent.com/62297116/117005148-7db91000-ad19-11eb-8d4c-31c99168eda3.png)
> 
> > ![image](https://user-images.githubusercontent.com/10571717/117000476-b655eb00-ad13-11eb-8227-edba40549683.png)
> > Hi, I am able to deploy Nobelium with your page id w/out issue. Could you try to deploy again?

Did you set NOTION_PAGE_ID properly?

**Comment by wz1616** [comment]
It's normal after I delete the project and redeploy it.
> > Nope yet!![image](https://user-images.githubusercontent.com/62297116/117005148-7db91000-ad19-11eb-8d4c-31c99168eda3.png)
> 
> > 
> 
> > > ![image](https://user-images.githubusercontent.com/10571717/117000476-b655eb00-ad13-11eb-8227-edba40549683.png)
> 
> > > Hi, I am able to deploy Nobelium with your page id w/out issue. Could you try to deploy again?
> 
> 
> 
> Did you set NOTION_PAGE_ID properly?

**Comment by craigary** [comment]
> It's normal after I delete the project and redeploy it.
> 
> > > Nope yet!![image](https://user-images.githubusercontent.com/62297116/117005148-7db91000-ad19-11eb-8d4c-31c99168eda3.png)
> > 
> > 
> > > 
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/10571717/117000476-b655eb00-ad13-11eb-8227-edba40549683.png)
> > 
> > 
> > > > Hi, I am able to deploy Nobelium with your page id w/out issue. Could you try to deploy again?
> > 
> > 
> > Did you set NOTION_PAGE_ID properly?

So I am gonna close this issue then.
