### ISSUE TITLE
Gitalk componment not refresh

### ISSUE THREAD

**Issue by alexlee-git** [craigary/nobelium#121]
**Describe the bug**
Gitalk Componment not refreshed and still showed the comments on the previous page.
It will show correctly when you refresh whole page.

**To Reproduce**
Click on Page A to  load the comments,then click page B

**Expected behavior**
Show the correct comments on the page

**Screenshots**
https://www.v2ca.ca/EE

![image](https://user-images.githubusercontent.com/15151031/118207839-1842ed00-b498-11eb-8051-8065b4989d50.png)

![image](https://user-images.githubusercontent.com/15151031/118207855-21cc5500-b498-11eb-8c26-4bb2847d2c29.png)

**Platform:**

- OS: macOS
- Browser :chrome
- Version :1.3.0

**Additional context**
N/A

**Comment by craigary** [comment]
Hi, Thank you for reporting this issue, I'll dig into it later.
