### ISSUE TITLE
code block text color in dark mode NOT FIXED

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#129]
**Describe the bug**

- code block colour scheme is still the same in both mode

**To Reproduce**

- swith between dark/light
- code block remains untouched

**Expected behavior**

- use a dark theme for code block in dark mode

**Screenshots**

**Platform:**

- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by craigary** [comment]
Currently code block is working as intended, because I don't want to keep two prismjs css at the same time. 

I will take a look in the future, meanwhile, how about switch to a dark prismjs CSS theme instead?
