### ISSUE TITLE
Add support for giscus as comments provider

### ISSUE THREAD

**Issue by laymonage** [craigary/nobelium#132]
**Is your feature request related to a problem? Please describe.**
Gitalk and utterances are great, but they (ab)use GitHub Issues. Given enough time, they would flood the repository's issues.

**Describe the solution you'd like**
Add support for [giscus](https://giscus.vercel.app), a comments widget powered by GitHub Discussions.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Thanks!

**Comment by craigary** [comment]
Hi, Thank you for the suggestion, It seems nice! I will add giscus later, but I don't have ETA for now.

and yes, I agree gitalk and utterances are abusing GitHub Issue, and I don't use it personally. I suggest take a look at cusdis, it might be a better option imo.

**Comment by craigary** [comment]
And oh, you're the dev of giscus, I will definitely take a look~

**Comment by laymonage** [comment]
Ah, yes, I probably should've mentioned that 😅
Thanks!
