### ISSUE TITLE
please add tweet embeds.

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#133]
**Is your feature request related to a problem? Please describe.**

- i really want twitter embed in the post

**Describe the solution you'd like**

- show tweets

**Describe alternatives you've considered**

- /

**Additional context**

- fyi: https://github.com/NotionX/react-notion-x/issues/48#issuecomment-808757234

**Comment by craigary** [comment]
Sure, I will take a look, and see if I can implement that.
