### ISSUE TITLE
Code area in li tag will expand the width of device, so the mobile device to be unable to view normally

### ISSUE THREAD

**Issue by xukecheng** [craigary/nobelium#137]
**Describe the bug**
Code area in li tag will expand the width of device, so the mobile device to be unable to view normally

**Expected behavior**
Wish the max width will be restricted

**Screenshots**
![65483d2322f2c183c1aa77aa13f5fb1](https://user-images.githubusercontent.com/29099863/119755882-564b0280-bed5-11eb-8065-d4ff5da9e278.jpg)
![d691832065aee130892490b21450604](https://user-images.githubusercontent.com/29099863/119755909-5e0aa700-bed5-11eb-9ef9-cd247db2889e.jpg)

**Platform:**

- OS: Android
- Browser Edge
- Version MIUI 12.5 Andoird 11 Edge 46.04.4.5157

**Additional context**

**Comment by craigary** [comment]
This is a known issue, see NotionX/react-notion-x#67

**Comment by SilentDepth** [comment]
This has been fixed.
