### ISSUE TITLE
Hello, I have a question about the failure of deployment in vercel

### ISSUE THREAD

**Issue by AirDia** [craigary/nobelium#143]
I have the following errors in the deployment of vercel, which lead to the correct deployment. I hope you can solve my problems. Thank you very much

18:39:32.295 | pageId "7a69a86e-a02c-4505-880c-82b1b02ba7cb" is not a database
-- | --
18:39:32.296 | &gt; Build error occurred
18:39:32.298 | TypeError: Cannot read property 'filter' of null
18:39:32.298 | at getStaticPaths (/vercel/path0/.next/server/pages/page/[page].js:69:17)
18:39:32.299 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
18:39:32.299 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
18:39:32.299 | at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
18:39:32.299 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584) {
18:39:32.299 | type: 'TypeError'
18:39:32.299 | }
18:39:32.345 | error Command failed with exit code 1.
18:39:32.345 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:39:32.363 | Error: Command "yarn run build" exited with 1

**Comment by craigary** [comment]
Hi, seems like the page id you put into the environment variable is not correct, please duplicate the template from the README.MD file, and put its pageid into the environment variable.

**Comment by AirDia** [comment]
> Hi, seems like the page id you put into the environment variable is not correct, please duplicate the template from the README.MD file, and put its pageid into the environment variable.

I missed this step and now it has been successfully built. Thank you for your reply. Thank you very much
