### ISSUE TITLE
Vercel被墙，请问是否有计划部署至其他平台

### ISSUE THREAD

**Issue by 1eif** [craigary/nobelium#145]
**Is your feature request related to a problem? Please describe.**
Vercel在大陆被墙

**Describe the solution you'd like**
Serverless、docker等

**Describe alternatives you've considered**

**Additional context**

**Comment by craigary** [comment]
Nobelium is built on next.js, and it's nice to deploy on vercel, the same company develops next.js.

You can try to deploy on other hosting platforms if you'd like, but I will always recommend using Vercel for deploy next.js project.

**Comment by yrucrew** [comment]
https://www.vercel-status.com/incidents/r758bhbklgfd
@1eif 参考这个链接可以解决 Vercel 国内访问的问题
