### ISSUE TITLE
Embedded item in Toggle not 100% width

### ISSUE THREAD

**Issue by designedbyclu** [craigary/nobelium#149]
**Describe the bug**
The embedded item (iframe) inside unable 100% width

**To Reproduce**
Example of Spotify Web Player
1. Copy Spotify Code
2. Copy URL
3. Pasted in toggle

**Expected behavior**
Show in 100% width.

**Screenshots**
![image](https://user-images.githubusercontent.com/26009982/123543433-fe781380-d780-11eb-8bb8-57adc1f9fdca.png)

**Platform:**

- OS: macOS Big Sur
- Browser: Chrome, Brave, Safari

**Comment by craigary** [comment]
Hmmmm, Let me take a look~

**Comment by craigary** [comment]
<img width="818" alt="Screen Shot 2021-06-27 at 21 26 02" src="https://user-images.githubusercontent.com/10571717/123546229-4f423900-d78e-11eb-8070-085544f6b900.png">

Looks fine on my side, weird....

**Comment by designedbyclu** [comment]
Adjust widget width can fix the error.
