### ISSUE TITLE
Toggle background color didn't function well

### ISSUE THREAD

**Issue by chiperman** [craigary/nobelium#158]
**Is your feature request related to a problem? Please describe.**
- I gave a background-color to the toggle, but it didn't appear in the nobelium.

**Describe the solution you'd like**
- Add the background-color to the toggle.

**Additional context**
The first img is what I write in the notion
<img width="736" alt="截屏2021-08-13 上午10 30 27" src="https://user-images.githubusercontent.com/34889778/129296808-496cac9a-5ad3-4c8c-89c9-023d9d3bd24f.png">

the second img is what I see in nobelium
<img width="430" alt="截屏2021-08-13 上午10 30 52" src="https://user-images.githubusercontent.com/34889778/129296812-7306f15a-1ee3-4e8f-9d3c-79787da483e8.png">

**Comment by craigary** [comment]
Hi there, sorry for the late reply. Unfortunately I couldn't find a good workaround about this at the moment. I might tweak about it in the future~

**Comment by SilentDepth** [comment]
Hi! I know it’s so late but we have added the background support for toggle blocks! Hope you enjoy!
