### ISSUE TITLE
Error Pages and Invisible Buttons

### ISSUE THREAD

**Issue by kaiyao7** [craigary/nobelium#161]
### A invisible button there and I clicked be like ......

**exp** & **Describe the bug** & **Screenshots** :

![544](https://user-images.githubusercontent.com/61994327/130184870-e0900184-60fb-41bf-848c-a12c7990abc9.gif)
### Also, I did not modify [Pagination.js](https://github.com/craigary/nobelium/blob/main/components/Pagination.js) & there are no extra blank pages in my NOBELIUM Tamplate.

**Platform:**
- OS: Windows 10 Pro N
- Browser: Chrome latest version.

**Comment by craigary** [comment]
Solved in #428
