### ISSUE TITLE
Trobles w/ cacheable-lookup: Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by a-x-** [craigary/nobelium#162]
**Describe the bug**
doesn't build

**To Reproduce**
1. I run yarn && yarn dev
2. when build complete,
3. browser shows: 'Module not found: Can't resolve 'dns''. Also I see many similar errors in console

**Expected behavior**
I must see my notion mirror site

**Screenshots**
<img width="983" alt="Screenshot 2021-08-21 at 20 15 52" src="https://user-images.githubusercontent.com/6201068/130416685-094fda89-5bb4-4a95-93b6-d85dd460980f.png">

**Platform:**

- **OS**: macOS
- **Browser** N/A, chrome, any other will so
- **Version** N/A

**Additional context**
repo: https://github.com/a-x-/nobelium

**Comment by a-x-** [comment]
anyone?

**Comment by a-x-** [comment]
help

**Comment by a-x-** [comment]
is this project still maintaining?

**Comment by adithyaakrishna** [comment]
Yo @a-x- Try updating the cacheable-lookup module to the latest version
Sometimes this has solved my problem :)

**Comment by craigary** [comment]
Hi there, sorry for the late reply. Can you try to clone and run again? it's working on my side~
