### ISSUE TITLE
Attempt to add FR as French; need help to understand my mistake before PR

### ISSUE THREAD

**Issue by JOduMonT** [craigary/nobelium#164]
I basically replicated what [@GermanHeim](https://github.com/craigary/nobelium/pull/155) did with Spanish but when I generate my website, only the next.js part is translated, and what is in lang.js js ignored. So before doing my PR I would like to make it work ;)
![image](https://user-images.githubusercontent.com/5204724/130939275-dc16e033-4f36-4c7a-a2ea-7ab267303794.png)

- [my line 7 in blog.config](https://github.com/JOduMonT/nobelium/blob/main/blog.config.js#L7) is now:
 `lang: 'fr-CA', // ['en-US', 'zh-CN', 'zh-HK', 'zh-TW', 'ja-JP', 'es-ES', 'fr-FR', 'fr-CA']`
- [and I added those line in ./lib/lang.js for French](https://github.com/JOduMonT/nobelium/blob/main/lib/lang.js#L100-L115)
```
  fr: {
    NAV: {
      INDEX: 'Blog',
      RSS: 'RSS',
      SEARCH: 'Chercher',
      ABOUT: 'À propos'
    },
    PAGINATION: {
      PREV: 'Précédent',
      NEXT: 'Suivant'
    },
    POST: {
      BACK: 'Retour',
      TOP: 'Haut'
    }
  }
```
...
```
    case 'fr':
    case 'fr-CA':
    case 'fr-FR':
      return lang.fr
```

**Comment by craigary** [comment]
weird, sorry for the late reply, I'll take a look tomorrow~

**Comment by craigary** [comment]
<img width="238" alt="Screen Shot 2021-09-06 at 23 32 03" src="https://user-images.githubusercontent.com/10571717/132239459-a031c842-b0a5-4bd8-a1e2-9cdeddc33c09.png">
I guess you might need to use lower case instead, btw can you help me to fix case 'es-ES' to 'es-es' please 😃

**Comment by JOduMonT** [comment]
as @craigary mentioned;
in `lib/lang.js` language and country code have to be in **lowercase** (fr-fr, fr-ca, en-ca, en-uk, ...)
but  in `blog.config.js` it is fine to write the country in **UPPERCASE** (lang: 'fr-CA')
