### ISSUE TITLE
NotionAPI collectionQuery error Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by p0wer0ff** [craigary/nobelium#174]
When i deploy the blog ,i got the wrong info 
```
18:44:27.890 | NotionAPI collectionQuery error Response code 400 (Bad Request)
-- | --
18:44:27.892 | > Build error occurred
18:44:27.894 | TypeError: Cannot convert undefined or null to object
18:44:27.895 | at Function.values (<anonymous>)
18:44:27.895 | at getAllPageIds (/vercel/path0/.next/server/chunks/272.js:37:12)
18:44:27.896 | at getAllPosts (/vercel/path0/.next/server/chunks/272.js:186:21)
18:44:27.896 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
18:44:27.896 | at async getStaticPaths (/vercel/path0/.next/server/pages/tag/[tag].js:54:17)
18:44:27.896 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:472:31)
18:44:27.897 | at async /vercel/path0/node_modules/next/dist/build/utils.js:615:119
18:44:27.897 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20) {
18:44:27.897 | type: 'TypeError'
18:44:27.897 | }
18:44:27.954 | error Command failed with exit code 1.
18:44:27.955 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:44:27.985 | Error: Command "yarn run build" exited with 1
```
I think I have set the env  correctly,it still not work
![image](https://user-images.githubusercontent.com/34498885/136370656-2dacc155-9597-41ae-9fbd-5fef88b51452.png)

**Comment by waimao8** [comment]
我的也出现了这个问题

**Comment by p0wer0ff** [comment]
> > The same issues...
> > > It's due the notion api change. Updating notion-client to the latest version solves the problem. You can run `yarn upgrade notion-utils@latest` to manually fix it or wait for the repo owner to update.
> > 
> > 
> > The same issues... But I have updating notion-client to the latest version which is 8.0.0. Still not working...
> 
> You may get the wrong version. The latest version of notion-client is 4.9.7 (https://www.npmjs.com/package/notion-client). Yesterday I updated notion-client to 4.9.5 and It already worked.

thank you !
update the notion-client ,it works!
