### ISSUE TITLE
NotionAPI collectionQuery error Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by a-x-** [craigary/nobelium#178]
**Describe the bug**
When I run it, I get the error

**To Reproduce**
1. I forked a repo, specified a config and cloned a notion table.
2. I added `NOTION_PAGE_ID=bd12382834294cf681b356c3c7fd5fdc` into `.env.local`
3. I ran `yarn && next dev`

**Expected behavior**
Get local copy of you demo

**Screenshots**

**Platform:**

- OS: macOS
- Browser chrome
- Version latest

**Additional context**
https://www.notion.so/ru-tesla/bd12382834294cf681b356c3c7fd5fdc

https://github.com/a-x-/nobelium

**Comment by a-x-** [comment]
<img width="947" alt="Screenshot 2021-10-11 at 23 50 18" src="https://user-images.githubusercontent.com/6201068/136854041-3cef4b26-7800-4247-b187-ddffb6e360d7.png">

**Comment by draJiang** [comment]
> Perhaps that might be linked to this [#176 (comment)](https://github.com/craigary/nobelium/issues/176#issuecomment-939507606)
> 
> try to change the notion-client version in your [package.json file](https://github.com/craigary/nobelium/blob/main/package.json#L27) `"notion-client": "^4.9.3"`

it works 👍
