### ISSUE TITLE
vercel error

### ISSUE THREAD

**Issue by oozry12** [craigary/nobelium#18]
08:38:24 | > Build error occurred
-- | --
08:38:24 | Error [HTTPError]: Response code 400 (Bad Request)
08:38:24 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
08:38:24 | at processTicksAndRejections (internal/process/task_queues.js:93:5) {

**Comment by craigary** [comment]
Hi, can you share the full log during deployment?

**Comment by oozry12** [comment]
15:35:21.634 | > Build error occurred
-- | --
15:35:21.637 | Error [HTTPError]: Response code 400 (Bad Request)
15:35:21.638 | at Request.<anonymous> (/vercel/workpath0/node_modules/got/dist/source/as-promise/index.js:117:42)
15:35:21.638 | at processTicksAndRejections (internal/process/task_queues.js:97:5) {
15:35:21.638 | type: 'HTTPError',
15:35:21.638 | timings: {
15:35:21.638 | start: 1616571321475,
15:35:21.638 | socket: 1616571321475,
15:35:21.638 | lookup: 1616571321476,
15:35:21.638 | connect: 1616571321493,
15:35:21.638 | secureConnect: 1616571321512,
15:35:21.638 | upload: 1616571321512,
15:35:21.638 | response: 1616571321630,
15:35:21.638 | end: 1616571321631,
15:35:21.638 | phases: {
15:35:21.638 | wait: 0,
15:35:21.638 | dns: 1,
15:35:21.638 | tcp: 17,
15:35:21.638 | tls: 19,
15:35:21.638 | request: 0,
15:35:21.638 | firstByte: 118,
15:35:21.638 | download: 1,
15:35:21.638 | total: 156
15:35:21.638 | }
15:35:21.639 | }
15:35:21.639 | }
15:35:21.693 | npm ERR! code ELIFECYCLE
15:35:21.694 | npm ERR! errno 1
15:35:21.703 | npm ERR! nobelium@0.1.0 build: `next build`
15:35:21.704 | npm ERR! Exit status 1
15:35:21.704 | npm ERR!
15:35:21.704 | npm ERR! Failed at the nobelium@0.1.0 build script.
15:35:21.704 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:35:21.721 | npm ERR! A complete log of this run can be found in:
15:35:21.721 | npm ERR!     /vercel/.npm/_logs/2021-03-24T07_35_21_705Z-debug.log
15:35:21.733 | Error: Command "npm run build" exited with 1
15:35:25.961 | Done with "package.json"

**Comment by craigary** [comment]
Weird, I can't reproduce this, seems like it can't connect to the notion during the deployment.

Maybe try to run nobelium locally, don't forget to create env.local file with NOTION_PAGE_ID environment variable

**Comment by GoToBoy** [comment]
I have same question , I had add env 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/2384105/112304288-46961e80-8cd8-11eb-937a-e01483fed42a.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/2384105/112304333-557cd100-8cd8-11eb-970a-2b4a01cb687f.png">

this's my public page : https://www.notion.so/f66b5edd17964cbba76db33663462b0c?v=7d2c658586f14b6cb1f67c9645eaaaed

I copy last string '7d2c658586f14b6cb1f67c9645eaaaed' as env id

**Comment by craigary** [comment]
Oh, I see the problem, the Notion Page id should be 32 chars right after notion.so, in this case, the page should be `f66b5edd17964cbba76db33663462b0c`

@GoToBoy
