### ISSUE TITLE
能否指点下如何进行页面的美化,增加自定义内容

### ISSUE THREAD

**Issue by hpp0hpp** [craigary/nobelium#191]
能否指点下如何进行页面的美化,增加自定义内容 #191

**Comment by bulentala** [comment]
command+K menu would be very useful

**Comment by hpp0hpp** [comment]
> menu would be very useful

Sorry, where to do this?

**Comment by SilentDepth** [comment]
Nobelium 的样式主要由分散在 JSX 中的 Tailwind CSS utility classes、`styles` 目录下的 `globals.css` 和 `notion.css` 控制（以及 react-notion-x 提供的默认样式）。你可能需要修改多处代码来改变页面的外观。
