### ISSUE TITLE
是否可以添加一键回到页面顶端的功能……

### ISSUE THREAD

**Issue by hprandom** [craigary/nobelium#196]
**Is your feature request related to a problem? Please describe.**
现在Notion有了Toc块，但是既然不能放在页面一侧悬浮（始终保持在页面上），那一般都放在页面最上端。文章长一点的话，到了下面再回到顶端鼠标需要滚很久……

**Describe the solution you'd like**
所以，是否可以加一个点击按钮（悬浮再页面），可以一键回到页面最上端？

**Describe alternatives you've considered**
似乎没什么备选方案，最好的方案自然是整个TOC块可以悬浮……似乎更麻烦？

**Additional context**
没了……

**Comment by craigary** [comment]
好主意，不过请用英语书写，这样好帮助到其他人～

**Comment by craigary** [comment]
这几天加上～

**Comment by SilentDepth** [comment]
点击标题栏空白处滚动至顶如何？

**Comment by SilentDepth** [comment]
好吧。Nobelium 最近在重启维护。但如果你不想再迁移博客工具的话，祝你在其他工具用得愉快 😃
