### ISSUE TITLE
Can't show the title、description and the how to change the SVG icon in the header

### ISSUE THREAD

**Issue by chiperman** [craigary/nobelium#200]
**Describe the bug**
1. The title and the description cannot show unless I scroll down the page.
2. I can't change the default SVG in the header. I need to change into an IMG of my one Avatar.

**Expected behavior**
I want the title and description show all the time in the homepage and can change the SVG into IMG.

**Screenshots**
<img width="416" alt="截屏2022-01-01 下午4 40 59" src="https://user-images.githubusercontent.com/34889778/147847225-8d474a6a-e326-4aab-85dc-e826c45e702e.png">

<img width="371" alt="截屏2022-01-01 下午4 40 24" src="https://user-images.githubusercontent.com/34889778/147847196-ef623e18-7e68-4a14-adbd-274a8eb6b3a3.png">

<img width="456" alt="截屏2022-01-01 下午4 49 54" src="https://user-images.githubusercontent.com/34889778/147847284-337a2d13-5e02-4a20-b702-d381df50e11b.png">

**Comment by MiguelGalp** [comment]
The icon in the nav is a SVG element/tag in the Header.js component. If it makes any sense: you need to edit that file as a new commit into the main branch with whataver svg you like...sounds complicated if you have never done it before. Let me know though, I just did it in 5 minutes.

**Comment by 2ndMessiah** [comment]
Hey Chiperman!

I got the same exact two questions as above! As I have little knowledge of the front end, may I know your solution to the issues above?

Thanks!
