### ISSUE TITLE
Images cannot zoom

### ISSUE THREAD

**Issue by dingdingxia** [craigary/nobelium#202]
**Describe the bug**
I just follow the instructions in this repo to set up my blog. I found that the images in my post cannot zoom, but in the author's blog it can, e.g. the image in https://blog.craig.wf/nobelium-v130. It seems to be with class `medium-zoom-image` but i cannot find it in the codes. 
I wonder how to set up the zoom effect for the images? I'm really new to css/js stuff. 
Thanks!

**To Reproduce**
Check the images in my blog post: https://nobelium-test.vercel.app/test2

**Expected behavior**
Image zoom effect in https://blog.craig.wf/nobelium-v130

**Platform:**
- OS: macOS
- Browser: chrome

**Comment by Sanster** [comment]
I have the same problem, it's supposed to be a rendering issue with react-notion-x, but I upgraded it to the latest version (4.16.) and it still doesn't work

**Comment by dingdingxia** [comment]
@Sanster i upgraded react-notion-x to 6.0.17, as well as `notion-client`, `notion-utils` and the zoom effect works fine. some miner changes are required in `getAllPageIds.js` as the api now returns a bit different schema. but I just noticed that @craigary has updated accordingly. you may give it a try
