### ISSUE TITLE
The notion-bookmark-image could not be shown in vercel.app

### ISSUE THREAD

**Issue by eddiehe99** [craigary/nobelium#205]
**Is your feature request related to a problem? Please describe.**
I paste a link in the NOBELIUM Template page and choose to Create bookmark. 
But the image of the bookmark couldn't be shown in the vercel.app.

For instance, here is the [screenshot](https://user-images.githubusercontent.com/40681449/149321965-74c74532-df17-4c5d-9995-ba6815da3893.png) of the problem. 
<img width="841" alt="image" src="https://user-images.githubusercontent.com/40681449/149321965-74c74532-df17-4c5d-9995-ba6815da3893.png">
As is shown, the _About_ image displays well, but the bilibili image doesn't show up. 

**Describe the solution you'd like**
I hope other images of links could display perfectly like the _About_ image.

**Additional context**
Thanks for your time and patience. 
The class is equal to "notion-bookmark-image".

**Comment by SilentDepth** [comment]
Sorry for the delayed response. I cannot reproduce this issue at this time. Could you please check it again after updating your Nobelium version? And if the issue persists, could you provide a reproduction link?
![CleanShot 2023-03-16 at 18 09 09](https://user-images.githubusercontent.com/7194254/225584698-6bc49791-e341-4a60-b90d-b7ffab8dd897.png)
