### ISSUE TITLE
Support iframes

### ISSUE THREAD

**Issue by Enoch2090** [craigary/nobelium#206]
It would be nice if iframes in Notion notes can be parsed as is. For example, Deepnote allows its users to export a code block of the notebook as a embeddable iframe.

**Comment by SilentDepth** [comment]
Sorry for the delayed response. The embed block seems to work fine at this time. Could you please check it again after updating your Nobelium version? And if the issue persists, could you provide a reproduction link?

**Comment by Enoch2090** [comment]
I'm at the latest version now and it works. Thanks!
