### ISSUE TITLE
Toggle Head

### ISSUE THREAD

**Issue by hprandom** [craigary/nobelium#208]
**Describe the bug**
Toggle Head's content can not display.

**To Reproduce**

**Expected behavior**
Toggle Head's content can not display. I think you have already known about it. 

**Screenshots**

**Platform:**

- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by SilentDepth** [comment]
Sorry for the late response. I believe this issue has been fixed. Could you please check it again with an updated Nobelium?
