### ISSUE TITLE
Support mermaid.js preview

### ISSUE THREAD

**Issue by WingCH** [craigary/nobelium#213]
**Is your feature request related to a problem? Please describe.**
Now notion support mermaid diagram preview, but nobelium seems not yet supported.

**Describe the solution you'd like**
nobelium can preview mermaid diagram like notion 

**Describe alternatives you've considered**
manual output preview image and paste under code block 

**Additional context**

notion
![image](https://user-images.githubusercontent.com/19588517/151689958-3dd14fd8-3348-4ea6-b7d9-b10861bfb903.png)

nobelium
![image](https://user-images.githubusercontent.com/19588517/151689961-c2d2dd57-9355-4b1e-beca-2369aa026132.png)

**Comment by reycn** [comment]
这个工作是否应该由上游完成是一个问题。

**Comment by SilentDepth** [comment]
Upstream issue: https://github.com/NotionX/react-notion-x/issues/188
