### ISSUE TITLE
I wish nobelium can display mermaid

### ISSUE THREAD

**Issue by Ben9706** [craigary/nobelium#224]
I wish nobelium can display [mermaid](https://github.com/mermaid-js/mermaid),Since Notion had supported it.
<img width="812" alt="截屏2022-02-19 下午11 15 32" src="https://user-images.githubusercontent.com/47425245/154806850-49f6b2e3-279a-46d8-87d9-64d59132ba6d.png">

**Comment by yokinist** [comment]
Thanks for your suggestion.
Nobelium is using `react-notion-x` to render Notion content.
So, you need to follow the following issue. 👀

ref: https://github.com/NotionX/react-notion-x/issues/188
