### ISSUE TITLE
Using favicon.svg as nav bar icon, instead of the square

### ISSUE THREAD

**Issue by BeautyYuYanli** [craigary/nobelium#233]
**Is your feature request related to a problem? Please describe.**
I noticed that the icon on the [nav bar](https://github.com/craigary/nobelium/blob/5513bf847fa2d0c2bd97701cd64928ddcfca0c35/components/Header.js#L35) is a fixed square pattern. Using the favicon.svg uploaded by users may be better.

**Describe the solution you'd like**
I've changed it in [my blog](https://blog.beautyyu.one/) and it looks nice.

**Describe alternatives you've considered**

**Additional context**

**Comment by SilentDepth** [comment]
Hello! We have done some changes on this. Please see https://github.com/craigary/nobelium/issues/200#issuecomment-1484883410
