### ISSUE TITLE
long quote can't fully display

### ISSUE THREAD

**Issue by Rash10-d** [craigary/nobelium#251]
**Describe the bug**

a long and continuous quote in notion page can't fully display on the webpage that nobelium generated.

**To Reproduce**
1.start with a new page in the NOBELIUM Template named "long quote test", and paste some content in a long quote.
then set up all the notion properties.

2.go to the website,  check out the post, find it only displayed one paragraph.

**Expected behavior**
the web post which nobelium generated can fully display all of the content in a long quote, just like the original notion page's content.

**Screenshots**
1.![image](https://user-images.githubusercontent.com/75206698/192921278-7591e35e-807e-4bc2-a766-861ef2a481e7.png)
2.![image](https://user-images.githubusercontent.com/75206698/192921623-036f1f39-046d-481d-902e-044980ab2105.png)
**Platform:**
Browser: chrome&IOS safari
- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by SilentDepth** [comment]
I cannot reproduce this issue at this time. Could you please check it again after updating your Nobelium? And if the issue persists, could you provide a reproduction link?

**Comment by SilentDepth** [comment]
我尝试复制你提供的页面并交给 Nobelium 渲染，结果还是正常的。你有尝试更新 Nobelium 吗？也许新版修复了这个问题。
![CleanShot 2023-03-16 at 23 56 19](https://user-images.githubusercontent.com/7194254/225679228-f7e0ea4f-c9ae-4da0-a56e-8634aa52fe7e.png)

**Comment by Rash10-d** [comment]
抱歉，不太清楚怎么更新Nobelium，只是一开始fork了这个仓库，请教一下该怎么更新

**Comment by SilentDepth** [comment]
在你 fork 过去的 repo 里，你应该能看到一个 Sync fork 按钮（在 repo 首页文件列表右上方）。如果你没有对 Nobelium 的代码做任何修改（除了 `blog.config.js`），你应该能够直接更新，跟随界面指示操作就好。如果界面提示「This branch has conflicts」，那你就需要设法手动合并上游改动了，这可能需要你掌握 Git 操作技能。
