### ISSUE TITLE
slug is missing from og:url

### ISSUE THREAD

**Issue by Lastorder-DC** [craigary/nobelium#252]
**Describe the bug**
post slug is missing from og:url, resulting all embed linked to main page instead of post.

**To Reproduce**
1. Open demo blog post like [this](https://nobelium.vercel.app/what-make-vs-code)
2. og:url is set to `https://nobelium.vercel.app` (instead of `https://nobelium.vercel.app/what-make-vs-code`)

**Expected behavior**
og:url should be post link, not blog main page link

**Screenshots**
![chrome_2022-10-05_10-54-57](https://user-images.githubusercontent.com/18280396/193962683-fd0c76f6-dee6-41ef-b005-f4b9ac6c74a0.png)

**Platform:**

- OS: Windows
- Browser: Chrome
- Version: 106.0.5249.91

**Additional context**
I fixed by setting `Layout` tag slug to `frontMatter.slug` - See [this line](https://github.com/Lastorder-DC/blog.occm.cc/blob/main/layouts/layout.js#L29)

**Comment by Lastorder-DC** [comment]
This is not stale issue.

**Comment by Lastorder-DC** [comment]
Closed - Looks like repo is not actively on development.

**Comment by izuolan** [comment]
> Closed - Looks like repo is not actively on development.

Hello, it's easy to fix this problem.

In [Container.js](https://github.com/craigary/nobelium/blob/main/components/Container.js) first line add:
```
import { useRouter } from 'next/router'
```

In [line 9](https://github.com/craigary/nobelium/blob/main/components/Container.js#L9) below add:
```
const router = useRouter()
```

Edit [line 37](https://github.com/craigary/nobelium/blob/main/components/Container.js#L37) code:
```
      <meta
        property='og:url'
        content={meta.slug ? `${url}/${meta.slug}` : `${url}${router.asPath}`}
      />
```

<img width="647" alt="image" src="https://user-images.githubusercontent.com/5241553/196837515-520f8858-048a-4dd1-aa0b-6ac920a306ae.png">


Finally, if you are interested, you can refer to my fork project: [Notionic]()
