### ISSUE TITLE
Can't access to notion template page

### ISSUE THREAD

**Issue by phillip-101** [craigary/nobelium#258]
**Describe the bug**
when click the notion template link I can't access with no content error.
**To Reproduce**

**Expected behavior**
can I duplicate the tamplate?
**Screenshots**
![스크린샷 2022-11-26 오후 9 44 25](https://user-images.githubusercontent.com/78997057/204089578-7ccaf79c-1321-400d-9886-8356a9590096.png)

**Platform:**

- OS: macOS [e.g. iOS, Android, macOS]
- Browser Chrome[e.g. chrome, safari, firefox]

**Additional context**

**Comment by hhmy27** [comment]
also meet it problem

**Comment by hi-nikola** [comment]
template does not exist

**Comment by Zao-q** [comment]
https://craigary.notion.site/866916e3b939468b9b6f1d47dce99f9c

**Comment by hi-nikola** [comment]
> https://craigary.notion.site/866916e3b939468b9b6f1d47dce99f9c

谢谢。另外，我fork后，在vercel中deploy超时--Deployment failed with error。这是什么问题呢？
![image](https://user-images.githubusercontent.com/52887883/205007833-2c8f7015-1fc3-4ac7-abab-ef3ca9f8296c.png)

**Comment by hi-nikola** [comment]
other    https://github.com/tangly1024/NotionNext

**Comment by alerezaaa** [comment]
> > https://craigary.notion.site/866916e3b939468b9b6f1d47dce99f9c
> 
> 谢谢。另外，我fork后，在vercel中deploy超时--Deployment failed with error。这是什么问题呢？ ![image](https://user-images.githubusercontent.com/52887883/205007833-2c8f7015-1fc3-4ac7-abab-ef3ca9f8296c.png)

Hi
Please write in English to get answer sooner, its a international website

**Have you published your Page on Notion?** ("Share" button at top-right corner)

**Comment by hi-nikola** [comment]
> > > https://craigary.notion.site/866916e3b939468b9b6f1d47dce99f9c
> > 
> > 
> > 谢谢。另外，我fork后，在vercel中deploy超时--Deployment failed with error。这是什么问题呢？
> 
> Hi Please write in English to get answer sooner, its a international website
> 
> **Have you published your Page on Notion?** ("Share" button at top-right corner)
> 
> By the way, these are warning, not Error

Thanks for your help.
I  just checked the pageid, I have solved the problems.
Thank you very much
