### ISSUE TITLE
【Notion模板页面显示错误·The Templates page displays an error，it was unshared】

### ISSUE THREAD

**Issue by hang2048** [craigary/nobelium#261]
【QUESTION】
     Readme文件里提及到的需要复制并分享的Notion模板页面被取消分享了，
     能麻烦您再分享一次吗否则可能出现部署错误的现象。
The Templates page displays an error.
The Notion template pages mentioned in the document that needed to be copied and shared were unshared.
Could you please share it again, otherwise there may be a deployment error. 
【ScreenShot】
![image](https://user-images.githubusercontent.com/105864471/207040328-7c3906a1-bd05-4c60-a07f-896669dd52fd.png)

thank you so much.表示衷心的感谢

**Comment by abxm2** [comment]
It's the same case for roadmap URL below. These notion urls should be updated.

**Comment by phillip-101** [comment]
https://github.com/craigary/nobelium/pull/259
I upload fixed PR but not merged. check and go to fixed link

**Comment by SilentDepth** [comment]
This has been fixed.
