### ISSUE TITLE
Notion template link broken

### ISSUE THREAD

**Issue by jonmccon** [craigary/nobelium#265]
**Describe the bug**
Notion template that is mentioned in readme does not exist on notion anymore

**To Reproduce**
https://craigary.notion.site/adc3552cfc73442ab5048d4b1eb0079a 
Notion says this content does not exist

**Expected behavior**
Should load a template 

**Screenshots**

![Screenshot 2023-01-04 211441](https://user-images.githubusercontent.com/1914985/210706702-57d82540-2943-4238-a0d2-bc2796072d45.png)

**Platform:**

- OS: Windows 10
- Browser Chrome
- Version 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
I'm assuming the page got moved or replaced in notion and the readme just needs an update.

Excited to use this project, thank you for your work.

**Comment by jakernodle** [comment]
After reading through the code a bit to find the required fields I was able to remake what's needed to make it work. 
`https://equal-durian-2d2.notion.site/539c2d0c115c4ae1b175463f239b60d9?v=9f3fee0fad9244ff82a5077b8c5bc631`
The only thing I couldn't figure out is the difference between a Page and a Post. Seems like lib/notion/filterPublishedPosts.js was filtering for it so I added it in anyways. Oh 🐋!

> **Describe the bug** Notion template that is mentioned in readme does not exist on notion anymore
> 
> **To Reproduce** https://craigary.notion.site/adc3552cfc73442ab5048d4b1eb0079a Notion says this content does not exist
> 
> **Expected behavior** Should load a template
> 
> **Screenshots**
> 
> ![Screenshot 2023-01-04 211441](https://user-images.githubusercontent.com/1914985/210706702-57d82540-2943-4238-a0d2-bc2796072d45.png)
> 
> **Platform:**
> 
> * OS: Windows 10
> * Browser Chrome
> * Version 108.0.5359.125 (Official Build) (64-bit)
> 
> **Additional context** I'm assuming the page got moved or replaced in notion and the readme just needs an update.
> 
> Excited to use this project, thank you for your work.

**Comment by SilentDepth** [comment]
This has been fixed.
