### ISSUE TITLE
'ARG NOTION_PAGE_ID=' caused complie error in mac m1

### ISSUE THREAD

**Issue by ZENOTME** [craigary/nobelium#267]
**Describe the bug**
Machine: MAC M1 Pro
OS: Ventura 13.0.1 
Docker version 20.10.17, build 100c701

docker build will report error:
```
❯ docker build -t ${IMAGE} --build-arg NOTION_PAGE_ID .

[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                 0.0s
 => => transferring dockerfile: 869B                                                                 0.0s
 => [internal] load .dockerignore                                                                    0.0s
 => => transferring context: 2B                                                                      0.0s
  1 ARG NOTION_PAGE_ID
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 1: ARG names can not be blank
```

**Solution**
I modify `ARG NOTION_PAGE_ID=` into `ARG NOTION_PAGE_ID` and it works.
https://github.com/craigary/nobelium/blob/5513bf847fa2d0c2bd97701cd64928ddcfca0c35/Dockerfile#L1

**Comment by peizh** [comment]
Same error here on Mac M1 Max.
Then I removed the equal mark and got a new error on step 5/5 RUN yarn build:
```
#13 33.96 NotionAPI getSignedfileUrls error RequestError: Client network socket disconnected before secure TLS connection was established
#13 33.96     at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:962:111)
#13 33.96     at Object.onceWrapper (events.js:520:26)
#13 33.96     at ClientRequest.emit (events.js:412:35)
#13 33.96     at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
#13 33.96     at TLSSocket.socketErrorListener (_http_client.js:475:9)
#13 33.96     at TLSSocket.emit (events.js:400:28)
#13 33.96     at emitErrorNT (internal/streams/destroy.js:106:8)
#13 33.96     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
#13 33.96     at connResetException (internal/errors.js:639:14)
#13 33.96     at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
#13 33.96     at TLSSocket.emit (events.js:412:35)
#13 33.96     at endReadableNT (internal/streams/readable.js:1333:12)
#13 33.96     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
#13 33.96   code: 'ECONNRESET',

```

**Comment by ZENOTME** [comment]
Seems it caused by the some problem in network?

**Comment by GuYith** [comment]
> Same error here on Mac M1 Max.Mac M1 Max 上出现相同的错误。 Then I removed the equal mark and got a new error on step 5/5 RUN yarn build:然后我删除了相等的标记，并在第 5/5 步 RUN yarn 构建中得到一个新错误：
> 
> ```
> #13 33.96 NotionAPI getSignedfileUrls error RequestError: Client network socket disconnected before secure TLS connection was established
> #13 33.96     at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:962:111)
> #13 33.96     at Object.onceWrapper (events.js:520:26)
> #13 33.96     at ClientRequest.emit (events.js:412:35)
> #13 33.96     at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
> #13 33.96     at TLSSocket.socketErrorListener (_http_client.js:475:9)
> #13 33.96     at TLSSocket.emit (events.js:400:28)
> #13 33.96     at emitErrorNT (internal/streams/destroy.js:106:8)
> #13 33.96     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
> #13 33.96     at connResetException (internal/errors.js:639:14)
> #13 33.96     at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
> #13 33.96     at TLSSocket.emit (events.js:412:35)
> #13 33.96     at endReadableNT (internal/streams/readable.js:1333:12)
> #13 33.96     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
> #13 33.96   code: 'ECONNRESET',
> ```

Hi, I'm having the same problem running nobelium locally. Have you solved the problem?
