### ISSUE TITLE
You cannot access the template for notion, I don't know what fields to put. Unusuable

### ISSUE THREAD

**Issue by macromillion** [craigary/nobelium#268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform:**

- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by star-ll** [comment]
Hello, you can refer to this issue: #269

**Comment by SilentDepth** [comment]
This has been fixed.
