### ISSUE TITLE
Could you kindly re-share the link for the Notion template for nobelium, as the current one appears to be invalid?

### ISSUE THREAD

**Issue by Olgaron890406** [craigary/nobelium#269]
Hello

Could you kindly re-share the link for the Notion template for nobelium, as the current one appears to be invalid?

Orz

**Comment by star-ll** [comment]
Hello, you can refer to my blog：

[![pStH6AO.png](https://s1.ax1x.com/2023/01/25/pStH6AO.png)](https://imgse.com/i/pStH6AO)

Status field includes Idea, Draft, Revise, and Published.

Type field includes Post and Page.

**Comment by macromillion** [comment]
https://equal-durian-2d2.notion.site/539c2d0c115c4ae1b175463f239b60d9?v=9f3fee0fad9244ff82a5077b8c5bc631

**Comment by macromillion** [comment]
#271 pull request made here to address this bug

**Comment by SilentDepth** [comment]
This has been fixed.
