### ISSUE TITLE
Make the blog description text visible without scrolling down.

### ISSUE THREAD

**Issue by 2ndMessiah** [craigary/nobelium#273]
**Describe the bug**
The blog description in the header is invisible unless the page is scrolled down. The color of the description text is set to be consistent with the theme color which makes it invisible.

**To Reproduce**
step 1. Visit the nobelium blog site
step 2. Stay there and the description in the header is invisible.

**Expected behavior**
The description in the header is better visible on the main age at any condition.

**Screenshots**
![image](https://user-images.githubusercontent.com/22229188/215240959-1c2b7167-f016-46df-b81b-7bd1ac539553.png)

**Platform:**

- OS: macos12.6
- Browser chrome
- Version 109.0.5414.119

**Additional context**
Issue #200 raised the same question but was closed without a resolution.

**Comment by SilentDepth** [comment]
Hello! We have done some changes on this. Please see https://github.com/craigary/nobelium/issues/200#issuecomment-1484883410
