### ISSUE TITLE
Notion template: This content does not exist

### ISSUE THREAD

**Issue by MPThLee** [craigary/nobelium#275]
It's not a bug of code. but template.

**Describe the bug**
On Readme, "[this Notion template](https://craigary.notion.site/adc3552cfc73442ab5048d4b1eb0079a)" link is broken

**To Reproduce**
1. Click "[this Notion template](https://craigary.notion.site/adc3552cfc73442ab5048d4b1eb0079a)" on readme

**Expected behavior**
Template shows up

**Screenshots**
![image](https://user-images.githubusercontent.com/26970092/216944044-2bfc16ad-9934-4d55-8b83-8ee1e45b7703.png)

**Platform:**

- OS: Doesn't related
- Browser: Doesn't related
- Version: Doesn't related

**Comment by stuchilde** [comment]
how to find this notion template? @craigary

**Comment by CrazyCollin** [comment]
Same as your problem .

**Comment by adviks** [comment]
@craigary Please fix this issue.

**Comment by ggteixeira** [comment]
Same here :)

**Comment by SBFPGLN** [comment]
"You do not have access to CRAIG's BLOCK. Please contact an admin to add you as a member." how I should become the member: )

**Comment by designedbyclu** [comment]
Here is the template example:
https://whitesspace.notion.site/cc92abe4c3584e7186b0873bfa41751f?v=5cc83ea98e9845adb1124a99170ef342 

@MPThLee @stuchilde @adviks @ggteixeira @SBFPGLN

**Comment by est7** [comment]
@designedbyclu thank u

**Comment by SilentDepth** [comment]
This has been fixed.
