### ISSUE TITLE
部署到 vercel 报错失败

### ISSUE THREAD

**Issue by yefoenix** [craigary/nobelium#28]
部署日志：

> 09:47:48.496  	Cloning github.com/yefoenix/nobelium (Branch: main, Commit: 1a56904)
> 09:47:49.075  	Cloning completed in 579ms
> 09:47:49.078  	Analyzing source code...
> 09:47:49.481  	Installing build runtime...
> 09:47:51.398  	Build runtime installed: 1916.795ms
> 09:47:53.147  	Build cache not provided
> 09:47:53.876  	Installing dependencies...
> 09:47:54.221  	yarn install v1.22.10
> 09:47:54.286  	[1/4] Resolving packages...
> 09:47:54.535  	[2/4] Fetching packages...
> 09:48:06.916  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
> 09:48:06.916  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
> 09:48:06.926  	[3/4] Linking dependencies...
> 09:48:06.927  	warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
> 09:48:06.928  	warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
> 09:48:06.929  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
> 09:48:06.929  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
> 09:48:06.929  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
> 09:48:06.930  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
> 09:48:06.930  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
> 09:48:06.930  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
> 09:48:06.931  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
> 09:48:16.959  	[4/4] Building fresh packages...
> 09:48:18.195  	Done in 23.98s.
> 09:48:18.223  	Detected Next.js version: 10.0.7
> 09:48:18.224  	Running "yarn run build"
> 09:48:18.486  	yarn run v1.22.10
> 09:48:18.511  	$ next build
> 09:48:19.083  	info  - Creating an optimized production build...
> 09:48:19.100  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
> 09:48:19.100  	This information is used to shape Next.js' roadmap and prioritize features.
> 09:48:19.100  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> 09:48:19.100  	https://nextjs.org/telemetry
> 09:48:20.012  	info  - Using external babel configuration from /vercel/workpath0/.babelrc.js
> 09:48:20.437  	[styled-jsx] Loading plugin from path: /vercel/workpath0/node_modules/styled-jsx-plugin-postcss/index.js
> 09:48:40.270  	info  - Compiled successfully
> 09:48:40.271  	info  - Collecting page data...
> 09:48:41.508  	info  - Generating static pages (0/37)
> 09:48:43.385  	info  - Generating static pages (9/37)
> 09:48:44.045  	Unhandled error during request: TypeError: Cannot read property 'id' of undefined
> 09:48:44.046  	    at getStaticProps (/vercel/workpath0/.next/serverless/pages/[slug].js:1746:71)
> 09:48:44.046  	    at runMicrotasks (<anonymous>)
> 09:48:44.046  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 09:48:44.046  	    at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:28:109)
> 09:48:44.046  	    at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[slug].js:873:334)
> 09:48:44.046  	    at async /vercel/workpath0/node_modules/next/dist/export/worker.js:12:92
> 09:48:44.046  	    at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:3:470
> 09:48:44.046  	Error occurred prerendering page "/null". Read more: https://err.sh/next.js/prerender-error
> 09:48:44.046  	TypeError: Cannot read property 'id' of undefined
> 09:48:44.046  	    at getStaticProps (/vercel/workpath0/.next/serverless/pages/[slug].js:1746:71)
> 09:48:44.046  	    at runMicrotasks (<anonymous>)
> 09:48:44.046  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 09:48:44.046  	    at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:28:109)
> 09:48:44.047  	    at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[slug].js:873:334)
> 09:48:44.047  	    at async /vercel/workpath0/node_modules/next/dist/export/worker.js:12:92
> 09:48:44.047  	    at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:3:470
> 09:48:45.112  	info  - Generating static pages (18/37)
> 09:48:46.419  	info  - Generating static pages (27/37)
> 09:48:47.663  	info  - Generating static pages (37/37)
> 09:48:47.663  	> Build error occurred
> 09:48:47.665  	Error: Export encountered errors on following paths:
> 09:48:47.665  		/null
> 09:48:47.665  	    at /vercel/workpath0/node_modules/next/dist/export/index.js:30:1103
> 09:48:47.665  	    at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:3:470
> 09:48:47.665  	    at async /vercel/workpath0/node_modules/next/dist/build/index.js:39:69
> 09:48:47.665  	    at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:3:470
> 09:48:47.665  	    at async /vercel/workpath0/node_modules/next/dist/build/index.js:21:731
> 09:48:47.665  	    at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:3:470
> 09:48:47.727  	error Command failed with exit code 1.
> 09:48:47.727  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 09:48:47.739  	Error: Command "yarn run build" exited with 1
> 09:48:50.320  	Done with "package.json"

blog config：https://github.com/yefoenix/nobelium/blob/main/blog.config.js
notion 页面地址：https://www.notion.so/e7988de46ee34a78872ed12fb74f58eb

**Comment by yefoenix** [comment]
删除信息不完整的post之后部署成功，建议提示一下各

**Comment by dev-lake** [comment]
@yefoenix 你好！请问您是怎么解决的，能不能具体说一下。

**Comment by Pinocchia** [comment]
> 

回到你的notion database，把先有的文章全删掉，但是表格留着别删了！！然后安装，就成功了，能看见空白的博客。
你可以安装好了之后，再回notion里面点击撤销删除，然后再刷新页面，就是完整的范例博客。

我也不知道为啥会有这个bug，反正我是这么解决的。
