### ISSUE TITLE
Incorrect layout width in blog post page [slug]

### ISSUE THREAD

**Issue by AntDock** [craigary/nobelium#286]
**Describe the bug**
After syncing with the latest commit dac694d, the blog post page [slug] is shown at half the width of the browser.

**To Reproduce**
1.Deploy commit dac694d to Vercel and assign domains
2.Open any post page

**Expected behavior**
Correct behaviour can be seen at https://antdock.vercel.app/walking-away . This page is deployed on Vercel using instant rollback, thus avoiding the problem.

**Screenshots**
The problem can be visblily demonstrated with this page: https://nobelium-linfprg3n-antdock.vercel.app/walking-away

**Platform:**

- OS: All
- Browser: Chrome, Safari

**Comment by AntDock** [comment]
This issue may be caused by the changes in [slug].js made by @SilentDepth , please help inspect this. Many thanks!

**Comment by SilentDepth** [comment]
Do you mean the width of the comment section or am I missing something? The width of the comment section is indeed not right. I’ll fix it shortly.

**Comment by SilentDepth** [comment]
982e02a fixed the width issue. Does it solve this problem?

**Comment by AntDock** [comment]
Thank you. However, the width of the whole page seems to be off. I had made some changes to header.js and footer.js before, and also enabled Ackee in my forked repo (https://github.com/AntDock/nobelium). I only changed the logo and text in the navbar and footer. I'm not sure if that contributed to the problem. 

![Screenshot_20230321-120224](https://user-images.githubusercontent.com/67270559/226514670-f2a015b9-3ed6-4cae-8c68-566c1dca1fa3.png)

**Comment by AntDock** [comment]
I am deploying the new commit here. See if that can fix this.

**Comment by SilentDepth** [comment]
Ah, I see. The TOC doesn’t fit mobile screens right now. I’ll find a fix for that.

**Comment by AntDock** [comment]
No luck. The width problem persists.

**Comment by AntDock** [comment]
> Ah, I see. The TOC doesn’t fit mobile screens right now. I’ll find a fix for that.

Thank you.
