### ISSUE TITLE
Refresh in dark mode will flash a white background

### ISSUE THREAD

**Issue by Zao-q** [craigary/nobelium#292]
Refreshing the webpage under the dark theme will load the white theme first, and then load the black theme.
The previous version did not have this problem.

**Comment by Zao-q** [comment]
Thanks for the fix.
But now refresh in white mode will flash...

**Comment by SilentDepth** [comment]
OK, one more try

**Comment by Zao-q** [comment]
Refresh still flashes in white mode.

**Comment by SilentDepth** [comment]
How about this time

**Comment by Zao-q** [comment]
Looks fixed, thanks!
