### ISSUE TITLE
Headers in synced block cannot be recognised by TOC

### ISSUE THREAD

**Issue by ice-Yaya** [craigary/nobelium#296]
## Description of the bug
Headers in synced block cannot be recognised by TOC, including:
- Notion's native TOC and 
- Nobelium's floating TOC

## Expected behavior

TOC in Nobelium and in Notion page should look the same.

## Reproduction
1. Create a synced block
2. Create a heading inside the synced block in step 1
3. (Optional) Create a TOC block
4. Set status as `published` and check the page from Nobelium

## Screenshots

![CleanShot 2023-03-25 at 17 12 01@2x](https://user-images.githubusercontent.com/73091684/227708293-35cfe77a-c2d8-44b4-a0aa-7ed5134750fc.png)

**Comment by SilentDepth** [comment]
It’s an upstream issue. I expect react-notion-x would fix this.
