### ISSUE TITLE
KeTex parse error: {equation} can be used only in display mode

### ISSUE THREAD

**Issue by Rapisurazurite** [craigary/nobelium#306]
## Description of the bug

When rendering a "Math Equation" block, the displayed content is not centered. And the "equation" and other envs cannot be used, suggesting "that {equation} can be used only in display mode".

## Expected behavior

The display content is centered, and render in display mode.

## Reproduction

when redering a "Math Equation" block, and using {equation} env.

## Screenshots

![image](https://user-images.githubusercontent.com/43494437/230266106-e3cb9ca6-3de3-4eb7-a5b5-521977cbc6ff.png)
![image](https://user-images.githubusercontent.com/43494437/230266200-f83da308-5e92-4278-814d-671c689d240d.png)

## Software versions

  
- OS:
  
- Browser:
  
- Nobelium:

**Comment by SilentDepth** [comment]
Sorry, I’m not a TeX user. Could you please provide the TeX code of the reproduction? Then I’ll be able to debug this issue.
