### ISSUE TITLE
Add google analytics, google console search, comment systems like disqus,

### ISSUE THREAD

**Issue by Phonginhere** [craigary/nobelium#308]
## Describe the solution you’d like

Add google analytics, google console search, comment systems like disqus,

## Additional context

No additional context.

**Comment by SilentDepth** [comment]
We already support GA and Google Site Verification. About comment systems, we have built-in support for Gitalk, Utterances, and Cusdis. Both can be configured via `blog.config.js`. 

Currently, we don’t have an interest to add more comment systems to the codebase. Sorry about that.
