### ISSUE TITLE
Add  a new item in Navbar but don`t show

### ISSUE THREAD

**Issue by TOBEACODER7** [craigary/nobelium#309]
I want to add an item in the navbar named 'resume'. I added the page in Notion and I`ve gotten the page with lawrencee.top/resume.
But when I changed the code in Header.js like this :

![image](https://user-images.githubusercontent.com/60809993/230777867-52710004-defa-48cd-8f9e-92869bdd34d3.png)

The item cannot show. But the <a href> is right like this 

![image](https://user-images.githubusercontent.com/60809993/230777978-3b534497-1c68-4964-88f2-87dc3b38a0e7.png)

I tried to change the name with 'resume' like:
```{ id: 2, name: ’resume‘, to: '/resume', show: true },```
there still have errors.
I think locale is used to show text but I cannot find where I can add locale.NAV.RESUME

The error page is https://www.lawrencee.top/.
Hope someone can help me! Best wishes!

**Comment by SilentDepth** [comment]
In `assets/i18n/basic/en-US.json`, add a `"RESUME"` key under `"NAV"` and give it a string value `"Resume"` (or anything you’d like it to show). Note the quotes, it’s a JSON file and double quotes are required.
