### ISSUE TITLE
Error: The provided path `/B for Busy / Myth of Love` does not match the page: `/[slug]`.

### ISSUE THREAD

**Issue by HDS3991** [craigary/nobelium#311]
## Description of the bug
"Error: The provided path `/B for Busy / Myth of Love` does not match the page: `/[slug]`."

## Expected behavior

I want the project would be deploy success and show me website content.

## Reproduction

folk https://github.com/craigary/nobelium project and customize blog.config.js, deploy on [Vercel](https://vercel.com/), set NOTION_PAGE_ID environment variables.

## Screenshots

![Screen Shot 2023-05-15 at 14 32 39](https://github.com/craigary/nobelium/assets/29156418/13118435-8050-4a9c-bab7-6a1f77d90ab7)

**Comment by HDS3991** [comment]
same issue like https://github.com/orgs/vercel/discussions/133

**Comment by SilentDepth** [comment]
This is an intended behavior. `slug` is meant to be a valid URL segment. Thus you cannot use “URL-unsafe” characters here (e.g. spaces, slashes, etc.).
