### ISSUE TITLE
How can I use Notion Official API to  build this project ?Deploy failed on vercel.

### ISSUE THREAD

**Issue by Funnyyanne** [craigary/nobelium#328]
Sys: macOS 10.15.7 
Qusetion: I use notion Internal Integration API for this project , it can't be deploy on vercel.
The mistakes log:
<img width="747" alt="image" src="https://github.com/craigary/nobelium/assets/19363761/348a020a-894c-49d8-8b46-b20c2a63e85f">
I read the  document, did nobelium not support Notion Official API yet? Must I change to use the cookies to fix it?
When it will be supported？

**Comment by SilentDepth** [comment]
No, Nobelium only supports the Private API for now, as it uses notion-client internally which does not effectively support the Public API. The Public API really lacks lots of features that Nobelium needs. You probably could make Nobelium run on the Public API, but it takes lots of effort to re-implement the client-side API behaviors.

> When it will be supported?

At least when Notion increases the IO performance of the Public API (i.e. Bulk API). It was on the public roadmap page of developers.notion.com. But the page itself disappeared when I just re-checked the website. So I don’t know when it will be practical to support the Public API.
