### ISSUE TITLE
Notion template link is not working

### ISSUE THREAD

**Issue by mattteochen** [craigary/nobelium#344]
Hi guys,

Can you please update the Notion template link?

Thank you!

**Comment by Aurora82** [comment]
Up，please update template.

**Comment by XiandiShan** [comment]
I just found the new template link from a post on the demo site. Hope this helps you.
[New template link](https://craigary-old.notion.site/866916e3b939468b9b6f1d47dce99f9c?v=73fd891cab654e35b44893608a23760e)
