### ISSUE TITLE
vercel deployment failure

### ISSUE THREAD

**Issue by SherlockShemol** [craigary/nobelium#363]
## Description of the bug
I deploy nobelium but meet the problem and don't know where is wrong.
```
    at Request.<anonymous> (/vercel/path0/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1728712477169,
    socket: 1728712477171,
    lookup: 1728712477172,
    connect: 1728712477175,
    secureConnect: 1728712477183,
    upload: 1728712477183,
    response: 1728712477304,
    end: 1728712477306,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 1,
      tcp: 3,
      tls: 8,
      request: 0,
      firstByte: 121,
      download: 2,
      total: 137
    }
  }
}
> Build error occurred
Error: Failed to collect page data for /[slug]
    at /vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1217:15
```

## Software versions

  
- OS: Arch Linux
  
- Browser: Zen Browser
  
- Nobelium:

**Comment by SherlockShemol** [comment]
https://github.com/craigary/nobelium/issues/18

problem solved...Thank you.

**Comment by Tyruetrue** [comment]
how do you solve this , I have meet this issues too..

**Comment by SherlockShemol** [comment]
> how do you solve this , I have meet this issues too..

![image](https://github.com/user-attachments/assets/209dd4ea-80b8-4881-b142-c173f672cccb)
I mistakenly set the page id to the view id.I correct it and it works.

Hope it helps.

**Comment by Tyruetrue** [comment]
thx,but it seems I didn't set the wrong id QWQ

**Comment by SherlockShemol** [comment]
> thx,but it seems I didn't set the wrong id QWQ

another problem I met is during the initial deployment, the page id parameter I set does not take effect.I must add the page id parameter again in the settings then it finally works.

This is all I can help :rofl:  I hope your deployment goes smoothly and successfully.

**Comment by Tyruetrue** [comment]
yep,I did it and My blog have been built now
