### ISSUE TITLE
Support the Notion Serif Font

### ISSUE THREAD

**Issue by Boycottangent** [craigary/nobelium#45]
**Is your feature request related to a problem? Please describe.**
Hope for adding support for serif font in the notion page configuration. It's a very beautiful font for publishing-like page, especially for articles written in  Chinese or Japanese characters.

**Describe the solution you'd like**
Is possible to get the font configuration of certain notion pages and choose different fonts. Just like nobelium can use different page layout according to the notion's `Full-width` option.

**Describe alternatives you've considered**
A font type property (e.g default or serif) assigned to every pages can be an alternative but less graceful.

**Additional context**
an example of page using serif font
<img width="854" alt="image" src="https://user-images.githubusercontent.com/23280916/113677246-f5325a00-96ef-11eb-9383-cb5aee394cea.png">

**Comment by craigary** [comment]
Hi, unfortunately, To set serif font for an individual page will not be added for now. During the design process, Nobelium has always kept a clean design philosophy in mind, and we will not add too many useless features unless there is a clear usage scenario. 

Getting the font style for a single page is possible, but I can't find a scenario when it would be used.

In the future, perhaps an option to set the whole page to use serif or sans serif will be added. No specific timeline, though.
