### ISSUE TITLE
Automatic conversion of links to the blog posts

### ISSUE THREAD

**Issue by invisprints** [craigary/nobelium#70]
**Is your feature request related to a problem? Please describe.**
Notion uses [[ or @ to refer another pages. However, I find the nobelium could not conversion the notion links if it is refer to another posts within the blog. At the moment, it just jumps into notion pages.

**Describe the solution you'd like**
When I click the link, it could jumps into the correct post.

**Comment by craigary** [comment]
Hi, unfortunately, Automatic conversion of notion links to Nobelium pages will not be added for now. 

Nobelium is a Blogging platform, rather than 3rd party notion client. That's why we add features based on the needs of a blogging platform rather than implement all notion features.
