### ISSUE TITLE
Error: Command "next build" exited with 1

### ISSUE THREAD

**Issue by ankylau** [craigary/nobelium#72]
Vercel Deployment error: Error: Command "next build" exited with 1

**Comment by craigary** [comment]
Hi, unfortunately, nobody gonna help you if you don't show enough info.

Please post the log or screenshot.

**Comment by ankylau** [comment]
Thanks for your reply 

log:

23:55:32.684  	Cloning github.com/ankylau/nobelium (Branch: main, Commit: 4bca94c)
23:55:33.235  	Cloning completed in 551ms
23:55:33.238  	Analyzing source code...
23:55:33.647  	Installing build runtime...
23:55:35.538  	Build runtime installed: 1890.301ms
23:55:37.309  	Build cache not provided
23:55:38.076  	Installing dependencies...
23:55:38.439  	yarn install v1.22.10
23:55:38.526  	[1/4] Resolving packages...
23:55:38.777  	[2/4] Fetching packages...
23:55:53.037  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
23:55:53.037  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
23:55:53.044  	[3/4] Linking dependencies...
23:55:53.046  	warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x || 0.14.x || 15.x.x".
23:55:53.046  	warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x || 0.14.x || 15.x.x".
23:55:53.047  	warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
23:55:53.047  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
23:55:53.048  	warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
23:55:53.048  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
23:55:53.048  	warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
23:55:53.049  	warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
23:55:53.049  	warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
23:55:53.050  	warning " > eslint-config-standard@16.0.2" has incorrect peer dependency "eslint-plugin-promise@^4.2.1".
23:56:03.490  	[4/4] Building fresh packages...
23:56:03.512  	Done in 25.08s.
23:56:03.535  	Detected Next.js version: 10.1.3
23:56:03.745  	Running "next build"
23:56:04.756  	info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
23:56:04.932  	info  - Checking validity of types...
23:56:05.174  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
23:56:05.174  	This information is used to shape Next.js' roadmap and prioritize features.
23:56:05.174  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
23:56:05.174  	https://nextjs.org/telemetry
23:56:05.219  	info  - Creating an optimized production build...
23:56:09.876  	warn - You have enabled the JIT engine which is currently in preview.
23:56:09.876  	warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
23:56:30.109  	info  - Compiled successfully
23:56:30.110  	info  - Collecting page data...
23:56:30.761  	> Build error occurred
23:56:30.764  	Error [HTTPError]: Response code 400 (Bad Request)
23:56:30.765  	    at Request.<anonymous> (/vercel/workpath0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:56:30.765  	    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
23:56:30.765  	  type: 'HTTPError',
23:56:30.765  	  timings: {
23:56:30.765  	    start: 1618674990710,
23:56:30.765  	    socket: 1618674990711,
23:56:30.765  	    lookup: 1618674990711,
23:56:30.765  	    connect: 1618674990719,
23:56:30.766  	    secureConnect: 1618674990728,
23:56:30.766  	    upload: 1618674990728,
23:56:30.766  	    response: 1618674990758,
23:56:30.766  	    end: 1618674990758,
23:56:30.766  	    phases: {
23:56:30.766  	      wait: 1,
23:56:30.766  	      dns: 0,
23:56:30.766  	      tcp: 8,
23:56:30.766  	      tls: 9,
23:56:30.767  	      request: 0,
23:56:30.767  	      firstByte: 30,
23:56:30.767  	      download: 0,
23:56:30.767  	      total: 48
23:56:30.767  	    }
23:56:30.767  	  }
23:56:30.767  	}
23:56:30.806  	Error: Command "next build" exited with 1
23:56:33.498  	Done with "package.json"

**Comment by craigary** [comment]
Seems like you set wrong environment variable or didn't set at all

**Comment by ankylau** [comment]
I have set the environment variable but it doesn't seem to work

https://img11.360buyimg.com/ddimg/jfs/t1/161896/32/19732/133732/607c30eeE8cdf66b1/5ece60c3765b76b2.png
https://img14.360buyimg.com/ddimg/jfs/t1/157109/28/20104/57534/607c30eeEb206ac2d/1f7d71e54efdb677.png

**Comment by craigary** [comment]
Wrong page id, can't access through https://www.notion.so/852e84145945490b81253bbdfba85934

**Comment by ankylau** [comment]
It has been resolved, thank you very much for your help! The Chinese description seems to be wrong.
