### ISSUE TITLE
Fail to revise the date or add a new record

### ISSUE THREAD

**Issue by y-swim** [craigary/nobelium#74]
Hi, sometimes when I add a new record in the Notion and then delete it. Later, I add a record which contains some same slug of the deleted record. In this case, I click the new blog in the homepage, the details page does not update, which is still the deleted blog.

**Comment by craigary** [comment]
Hi, I will take a look, meanwhile, you can redeploy in Vercel dashboard to get the latest data.

**Comment by craigary** [comment]
Hi, sorry for the late reply, Nobelium has a lot code changed during the past two weeks, as I just tested, it seems like no longer an issue anymore.
