### ISSUE TITLE
please add utteranc.es for comments services

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#82]
**Is your feature request related to a problem? Please describe.**
well, I'm always frustrated when i see gitalk not utteranc.es

**Describe the solution you'd like**
add utteranc.es

**Describe alternatives you've considered**
set utteranc.es as the default provider

**Additional context**
/

**Comment by YUX** [comment]
it's a decent project btw.
good job

**Comment by craigary** [comment]
Hi, Thank you for the issue, utteranc.es will be added soon, comments is disabled by default ~

**Comment by craigary** [comment]
utterances is added #86
