### ISSUE TITLE
The Less code block do not display

### ISSUE THREAD

**Issue by lijiext** [craigary/nobelium#83]
**Describe the bug**

The Less code block do not display, If I turn the less or css block to text or qoute, It can be render correctly.
images follow:
![image](https://user-images.githubusercontent.com/47245992/116377594-eb5dcb80-a843-11eb-8a22-a91d766c6ec8.png)
The original notion page: 
[https://www.notion.so/Vue-Js-Loading-40d9bae0cef64fb2bf1a7280b10141e1](https://www.notion.so/Vue-Js-Loading-40d9bae0cef64fb2bf1a7280b10141e1)
The web page with error:
[https://blog.432000.xyz/vue-loading-mask](https://blog.432000.xyz/vue-loading-mask)

**To Reproduce**

copy a less code to notion, turn it to code block, select code type as 'less'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47245992/116378191-78a12000-a844-11eb-82e2-4094f170fdc5.png)

**Platform:**

- OS: [Windows NT 10.0; Win64; x64]
- Browser [ Chrome/90.0.4430.93 ]
- Version [Latest version]

**Additional context**

**Comment by craigary** [comment]
Hey, I believe this is not an issue of Nobelium, I can reproduce on my side with your page id, but when I duplicate this post to another database, everything is working fine. maybe you can create a new post / database to see if this still happen.

Less syntax highlight seems not working for now, I think it's an issue related to react-notion-x

**Comment by invisprints** [comment]
Hello, I also notice that python code blocks don't highlight keywords if I refresh the web several times.
**Screenshots**
<details>
  <summary>sample 1</summary>
<img width="655" alt="sample" src="https://user-images.githubusercontent.com/15833553/116521899-1f4df500-a907-11eb-9462-e543861142d5.png">
</details>

The original notion page:
https://www.notion.so/LSTM-A-29e09521d1ca4ac6aec275a8add7221d

The web page with error:
https://invisprints.vercel.app/LSTM-stock

And it almost don't work at dark mode.

**Comment by craigary** [comment]
> Hello, I also notice that python code blocks don't highlight keywords if I refresh the web several times.
> **Screenshots**
> sample 1
> <img alt="sample" width="655" src="https://user-images.githubusercontent.com/15833553/116521899-1f4df500-a907-11eb-9462-e543861142d5.png">
> 
> The original notion page:
> https://www.notion.so/LSTM-A-29e09521d1ca4ac6aec275a8add7221d
> 
> The web page with error:
> https://invisprints.vercel.app/LSTM-stock
> 
> And it almost don't work at dark mode.

I know, I believe this is related to react-notion-x. I'll report an issue when I have time.

I'm closing this, but I'll keep this in mind.

**Comment by wizyoung** [comment]
We can manually add language support by prismjs to solve this problem. See my following solutions here:

https://github.com/wizyoung/nobelium/blob/136585ffbf53f800d4fbbd2768b70370843e618b/pages/_app.tsx#L2-L10
