### ISSUE TITLE
post页面，进入的时候时候代码有语法高亮，刷新一下页面后，语法高亮就没了。。

### ISSUE THREAD

**Issue by anyanf** [craigary/nobelium#84]
**Describe the bug**
post页面，进入的时候时候代码有语法高亮，刷新一下页面后，语法高亮就没了。。

![image](https://user-images.githubusercontent.com/12234053/116381699-b9e6ff00-a847-11eb-98d1-750654d32202.png)

**Platform:**

- OS: iOS, macOS
- Browser edge

**Comment by craigary** [comment]
中文用户请注意：请仔细阅读以下模版，并使用英文描述问题。如果不遵循，issue 将会被关闭。

**Comment by anyanf** [comment]
> 中文用户请注意：请仔细阅读以下模版，并使用英文描述问题。如果不遵循，issue 将会被关闭。

已改
