### ISSUE TITLE
failed to show images

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#85]
**Describe the bug**
images failed to load

**To Reproduce**
insert a photo in Notion, then in nobelium it doesn't show as expected

**Expected behavior**
show pics as in Notion

**Screenshots**
<img width="1080" alt="Screen Shot 2021-04-28 at 5 36 12 PM" src="https://user-images.githubusercontent.com/10670661/116382268-501b2500-a848-11eb-92a8-ac2eef79539b.png">

**Platform:**
macOS firefox
- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by craigary** [comment]
Hi, would you mind to try to share the database to the public, and see if this still happen.

**Comment by YUX** [comment]
@craigary Many thanks for the prompt reply. The issue has solved when I share the db to the public.
