### ISSUE TITLE
Duplicate comment section

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#89]
**Describe the bug**
i can see two utterances comment section below the post

**To Reproduce**

1. open a post page, scroll down to the comment section.
2. navigate to another page, say About, then scroll down.
3. two utterances are there.

 

**Expected behavior**
one comment section

**Screenshots**
<img width="1080" alt="Screen Shot 2021-04-28 at 8 54 42 PM" src="https://user-images.githubusercontent.com/10670661/116407860-c88fdf00-a864-11eb-9549-af1b03b4aeba.png">

**Platform:**
macOS firefox/safari
- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by craigary** [comment]
No worries, I'll fix it tomorrow.

**Comment by YUX** [comment]
btw, i think there is too much blank space after the comment section.

**Comment by craigary** [comment]
Bug fixed (I have no idea what I was doing)
