### ISSUE TITLE
text colour is wrong when i disable dark mode

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#90]
**Describe the bug**
when I change `appearance` from `auto` to `light`, the text colour is still in dark mode, which is *light grey*, but it's supposed to be black, as in the light mode.

**To Reproduce**

1. set `appearance` to `light` in `blog.config.js`
2. set `Appearance` to `Light` in macOS System Preferences/General
3. open navigator to see a post, things should be normal as expected
4. set `Appearance` to `Dark` in macOS System Preferences/General
5. **see that post page again, the background colour is still white, but the text colour turns to light grey**

**Expected behavior**
test colour should be black when `appearance` is `light`

**Screenshots**
<img width="1080" alt="Screen Shot 2021-04-28 at 9 16 53 PM" src="https://user-images.githubusercontent.com/10670661/116410185-1b6a9600-a867-11eb-888d-4ea243a5899b.png">
<img width="1080" alt="Screen Shot 2021-04-28 at 9 17 05 PM" src="https://user-images.githubusercontent.com/10670661/116410196-1c9bc300-a867-11eb-9cd9-d9cee25e6d52.png">

**Platform:**
macOS firefox/safari (irrelevant)
- OS: [e.g. iOS, Android, macOS]
- Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by craigary** [comment]
Thank you~ It'll be fixed tomorrow.
